# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PSA
version:      0.49_01
version_from: lib/PSA.pm
installdirs:  site
requires:
    Class::Tangram:                1.5
    File::MMagic:                  1.15
    Maptastic:                     0
    Set::Object:                   1.04
    T2:                            0.08
    URI:                           1.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
